// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// Article is the golang structure for table article.
type Article internal.Article

// Fill with you ideas below.

//以下部分是Request传过来的BO

//接受的新增文章BO
type ArticleAddApiReq struct {
	ArticleTitle string `v:"required#文章标题不可为空"`
	UserId       int64  `v:"required#用户id不可为空"`
	Content      string `v:"required#文章内容不可为空"`
	Tags         []string
	Urls         []string
	ForumId      int64 `v:"required#文章所属论坛不可为空"`
}

//接收的更新文章BO
type ArticleUpdateApiReq struct {
	ArticleId    int64
	ArticleTitle string `v:"required#文章标题不可为空"`
	UserId       int64  `v:"required#用户id不可为空"`
	Content      string `v:"required#文章内容不可为空"`
	Tags         []string
	Urls         []string
	ForumId      int64 `v:"required#文章所属论坛不可为空"`
}

//接收删除文章的请求
type ArticleDelApiReq struct {
	UserId int64 `v:"required#删除需要用户id"`
	ArticleId int64 `v:"required:#删除对应的文章id"`
}

//以下部分是Reponse回去的VO

//文章博主信息
type ArticleUserInfo struct {
	UserId int
	Sex int
	Nickname string
	Avatar string
}

//返回文章详情
type ArticleProfileEntity struct {

}

//以下部分是参与Service的业务数据
