// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// ArticleLike is the golang structure for table article_like.
type ArticleLike internal.ArticleLike

// Fill with you ideas below.
