// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// ArticleLikeStat is the golang structure for table article_like_stat.
type ArticleLikeStat internal.ArticleLikeStat

// Fill with you ideas below.
