// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// CommentLikeStat is the golang structure for table comment_like_stat.
type CommentLikeStat internal.CommentLikeStat

// Fill with you ideas below.
