// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// CommentLike is the golang structure for table comment_like.
type CommentLike internal.CommentLike

// Fill with you ideas below.
//以下部分是Request传过来的BO

//点赞评论BO参数
type CommentLikeApiReq struct {
	UserId int //`v:"required#点赞需要用户id"`
	CommentId int `v:"required#点赞评论需要评论id"`
	Status int `v:"required#点赞需要状态"`
}

//以下部分是Reponse回去的VO


//以下部分是参与Service的业务数据