// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// Game is the golang structure for table game.
type Game internal.Game

// Fill with you ideas below.

//以下部分是Request传过来的BO

//以下部分是Reponse回去的VO

//游戏详情页
type GameProfile struct {
	Game *Game
	GameCommentScore *GameCommentScoreEntity
}

//卡片式游戏列表的简化Game信息
type GameInfo struct {
	GameId int
	GameName string
	Introduction string
	CoverImage string
}

//卡片式游戏列表的结构体信息
type GameMainRep struct {
	GameInfo *GameInfo
	Score float64
}

//卡片式游戏列表的结构体列表
type GameMainEntity struct {
	GameMainListRep []*GameMainRep
}


//以下部分是参与Service的业务数据
