// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// Game is the golang structure for table game.
type Game internal.Game

// Fill with you ideas below.

//以下部分是Request传过来的BO


//以下部分是Reponse回去的VO
type GameMainListRep struct {
	GameMainList []*Game
}


//以下部分是参与Service的业务数据
type Entity struct {
	Games *Game
}