// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// GameComment is the golang structure for table game_comment.
type GameComment internal.GameComment

// Fill with you ideas below.
