// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// Luntan is the golang structure for table luntan.
type Luntan internal.Luntan

// Fill with you ideas below.

//以下部分是Request传过来的BO


//以下部分是Reponse回去的VO

//返回的论坛查询数据
type LuntanRep struct {
	LuntanId   int64
	LuntanName string
	Tags       []string
	Shortdesc  string
	Icon       string
	GameId     int64
}

type LuntanEntity struct {
	LuntanRepList []*LuntanRep
}

//以下部分是参与Service的业务数据