// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"san616qi/app/model/internal"
)

// User is the golang structure for table user.
type User internal.User

// Fill with you ideas below.

//以下部分是Request传过来的BO

//注册表单提交参数
type UserApiSignUpReq struct {

	Passport  string `v:"required|length:6,16#账号不能为空|账号长度应当在:min到:max之间"`
	Password  string `v:"required|length:6,16#请输入确认密码|密码长度应当在:min到:max之间"`
	Password2 string `v:"required|length:6,16|same:Password#密码不能为空|密码长度应当在:min到:max之间|两次密码输入不相等"`
	Nickname  string

}

//以下部分是Reponse回去的VO


//以下部分是参与Service的业务数据



