// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Article is the golang structure for table article.
type Article struct {
	ArticleId    int64       `orm:"article_id,primary" json:"articleId"`    //
	ArticleTitle string      `orm:"article_title"      json:"articleTitle"` //
	UserId       int64       `orm:"user_id"            json:"userId"`       //
	Content      string      `orm:"content"            json:"content"`      //
	Tags         string      `orm:"tags"               json:"tags"`         //
	Urls         string      `orm:"urls"               json:"urls"`         //
	CreateAt     *gtime.Time `orm:"create_at"          json:"createAt"`     //
	UpdateAt     *gtime.Time `orm:"update_at"          json:"updateAt"`     //
	ForumId      int64       `orm:"forum_id"           json:"forumId"`      //
}
