// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CommentLike is the golang structure for table comment_like.
type CommentLike struct {
	CommentLikeId   int64       `orm:"comment_like_id,primary" json:"commentLikeId"`   //
	UserId          int64       `orm:"user_id"                 json:"userId"`          //
	CommentId       int64       `orm:"comment_id"              json:"commentId"`       //
	CommentLikeStat int         `orm:"comment_like_stat"       json:"commentLikeStat"` //
	CommentLikeTime *gtime.Time `orm:"comment_like_time"       json:"commentLikeTime"` //
	CreateAt        *gtime.Time `orm:"create_at"               json:"createAt"`        //
	UpdateAt        *gtime.Time `orm:"update_at"               json:"updateAt"`        //
}
