// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CommentLikeStat is the golang structure for table comment_like_stat.
type CommentLikeStat struct {
	CommentLikeStat int64       `orm:"comment_like_stat,primary" json:"commentLikeStat"` //
	CommentId       int64       `orm:"comment_id"                json:"commentId"`       //
	LikeCount       int         `orm:"like_count"                json:"likeCount"`       //
	CreateAt        *gtime.Time `orm:"create_at"                 json:"createAt"`        //
	UpdateAt        *gtime.Time `orm:"update_at"                 json:"updateAt"`        //
}
