// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Game is the golang structure for table game.
type Game struct {
	GameId         int64       `orm:"game_id,primary" json:"gameId"`         //
	GameName       string      `orm:"game_name"       json:"gameName"`       //
	ReleaseAt      *gtime.Time `orm:"release_at"      json:"releaseAt"`      //
	Author         string      `orm:"author"          json:"author"`         //
	Introduction   string      `orm:"introduction"    json:"introduction"`   //
	Classification int         `orm:"classification"  json:"classification"` //
	CoverImage     string      `orm:"cover_image"     json:"coverImage"`     //
	DetailImages   string      `orm:"detail_images"   json:"detailImages"`   //
	Tags           string      `orm:"tags"            json:"tags"`           //
}
