// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Luntan is the golang structure for table luntan.
type Luntan struct {
	LuntanId   int64  `orm:"luntan_id,primary" json:"luntanId"`   //
	LuntanName string `orm:"luntan_name"       json:"luntanName"` //
	Tags       string `orm:"tags"              json:"tags"`       //
	Shortdesc  string `orm:"shortdesc"         json:"shortdesc"`  //
	Icon       string `orm:"icon"              json:"icon"`       //
	GameId     int64  `orm:"game_id"           json:"gameId"`     //
}
