// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	UserId       int64       `orm:"user_id,primary" json:"userId"`       //
	Sex          int         `orm:"sex"             json:"sex"`          //
	Nickname     string      `orm:"nickname"        json:"nickname"`     //
	Avatar       string      `orm:"avatar"          json:"avatar"`       // 用户头像地址，考虑实现
	Password     string      `orm:"password"        json:"password"`     //
	Phone        string      `orm:"phone"           json:"phone"`        //
	Introduction string      `orm:"introduction"    json:"introduction"` //
	Location     string      `orm:"location"        json:"location"`     //
	Birthday     *gtime.Time `orm:"birthday"        json:"birthday"`     //
	LastAccessAt *gtime.Time `orm:"last_access_at"  json:"lastAccessAt"` //
	CreateAt     *gtime.Time `orm:"create_at"       json:"createAt"`     //
	Passport     string      `orm:"passport"        json:"passport"`     //
}
