# HTTP Server.
[server]
	address        = ":8199"
	serverRoot     = "public"
	serverAgent    = "gf-demos"
	logPath        = "/Users/lujunliang/go/src/san616qi/log/server"
	nameToUriType  = 2
	routeOverWrite = true

# Logger configurations.
[logger]
    path   = "/Users/lujunliang/go/src/san616qi/log"
    level  = "all"
    stdout = true


# Template view configurations.
[viewer]
    path        = "template"
    defaultFile = "index.html"

# Database configurations.
[database]
    link  = "mysql:root:123456@tcp(127.0.0.1:3306)/sanqi"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/gf-demos/sql"
        Level  = "all"
        Stdout = true

[redis]
    default = "127.0.0.1:6379,0"
    cache   = "127.0.0.1:6379,1,123456?idleTimeout=600"

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)

[[gfcli.gen.dao]]
link   = "mysql:root:123456@tcp(127.0.0.1:3306)/sanqi"
tables = "comment_like"

[[gfcli.gen.dao]]
link   = "mysql:root:123456@tcp(127.0.0.1:3306)/sanqi"
tables = "comment_like_stat"