// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"san616qi/app/dao/internal"
)

// commentLikeStatDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type commentLikeStatDao struct {
	*internal.CommentLikeStatDao
}

var (
	// CommentLikeStat is globally public accessible object for table comment_like_stat operations.
	CommentLikeStat commentLikeStatDao
)

func init() {
	CommentLikeStat = commentLikeStatDao{
		internal.NewCommentLikeStatDao(),
	}
}

// Fill with you ideas below.
