// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"san616qi/app/dao/internal"
)

// luntanDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type luntanDao struct {
	*internal.LuntanDao
}

var (
	// Luntan is globally public accessible object for table luntan operations.
	Luntan luntanDao
)

func init() {
	Luntan = luntanDao{
		internal.NewLuntanDao(),
	}
}

// Fill with you ideas below.
