// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ArticleLikeStatDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ArticleLikeStatDao struct {
	gmvc.M                         // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                 // DB is the raw underlying database management object.
	Table   string                 // Table is the table name of the DAO.
	Columns articleLikeStatColumns // Columns contains all the columns of Table that for convenient usage.
}

// ArticleLikeStatColumns defines and stores column names for table article_like_stat.
type articleLikeStatColumns struct {
	ArticleLikeStatusId string //
	ArticleId           string //
	LikeCount           string //
	CreateAt            string //
	UpdateAt            string //
}

func NewArticleLikeStatDao() *ArticleLikeStatDao {
	return &ArticleLikeStatDao{
		M:     g.DB("default").Model("article_like_stat").Safe(),
		DB:    g.DB("default"),
		Table: "article_like_stat",
		Columns: articleLikeStatColumns{
			ArticleLikeStatusId: "article_like_status_id",
			ArticleId:           "article_id",
			LikeCount:           "like_count",
			CreateAt:            "create_at",
			UpdateAt:            "update_at",
		},
	}
}
