// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ArticleLikeDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ArticleLikeDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns articleLikeColumns // Columns contains all the columns of Table that for convenient usage.
}

// ArticleLikeColumns defines and stores column names for table article_like.
type articleLikeColumns struct {
	ArticleLikeId     string //
	UserId            string //
	ArticleId         string //
	ArticleLikeStatus string //
	ArticleLikeTime   string //
	CreateAt          string //
	UpdateAt          string //
}

func NewArticleLikeDao() *ArticleLikeDao {
	return &ArticleLikeDao{
		M:     g.DB("default").Model("article_like").Safe(),
		DB:    g.DB("default"),
		Table: "article_like",
		Columns: articleLikeColumns{
			ArticleLikeId:     "article_like_id",
			UserId:            "user_id",
			ArticleId:         "article_id",
			ArticleLikeStatus: "article_like_status",
			ArticleLikeTime:   "article_like_time",
			CreateAt:          "create_at",
			UpdateAt:          "update_at",
		},
	}
}
