// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// LuntanDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type LuntanDao struct {
	gmvc.M                // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB        // DB is the raw underlying database management object.
	Table   string        // Table is the table name of the DAO.
	Columns luntanColumns // Columns contains all the columns of Table that for convenient usage.
}

// LuntanColumns defines and stores column names for table luntan.
type luntanColumns struct {
	LuntanId   string //
	LuntanName string //
	Tags       string //
	Shortdesc  string //
	Icon       string //
	GameId     string //
}

func NewLuntanDao() *LuntanDao {
	return &LuntanDao{
		M:     g.DB("default").Model("luntan").Safe(),
		DB:    g.DB("default"),
		Table: "luntan",
		Columns: luntanColumns{
			LuntanId:   "luntan_id",
			LuntanName: "luntan_name",
			Tags:       "tags",
			Shortdesc:  "shortdesc",
			Icon:       "icon",
			GameId:     "game_id",
		},
	}
}
